### ISSUE TITLE
論文のタイトルを翻訳したほうがよいか

### ISSUE THREAD

**Issue by wakamezake** [fkubota/Carrier-Owl#54]

**Comment by fkubota** [comment]
僕も少し迷っています。。。  
urlクリックすれば見れるのでいいかなとは思ってるんですが。  
少し考えます。

**Comment by amaotone** [comment]
config.ymlでどういう要素を表示するか選べるようにすると解決すると思いました。

▼イメージ
```
display:
  score: true
  keywords: true
  url: true
  title_en: true
  title_ja: true
  abstract_en: false
  abstract_ja: true
```
